# Generated by Django 5.1 on 2025-04-30 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=50)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('ocupada', 'Ocupada'), ('disponible', 'Disponible')], max_length=10)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('tipo_usuario', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador')], max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MiApp.usuario')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('preferencias', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_reserva', models.CharField(max_length=50)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.habitacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado_pago', models.CharField(max_length=50)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialReserva',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.usuario')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.reserva')),
            ],
        ),
    ]
