# Generated by Django 5.1 on 2025-04-30 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_usuario_is_active_usuario_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
    ]
